spring:
  config:
    import: classpath:secrets.properties
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/